package com.cn.jblog.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("jblog_article_main", "article_Id", ArticleMain.class);
		arp.addMapping("jblog_article_temp", "temp_Id", ArticleTemp.class);
		arp.addMapping("jblog_left_bar_class", "class_Id", LeftBarClass.class);
		arp.addMapping("jblog_upload_img", "img_Id", UploadImg.class);
		arp.addMapping("jblog_user", "user_Id", User.class);
	}
}

