package com.cn.jblog.model;

import com.cn.jblog.model.base.BaseArticleMain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleMain extends BaseArticleMain<ArticleMain> {
	
}
