package com.cn.jblog.model;

import com.cn.jblog.model.base.BaseLeftBarClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeftBarClass extends BaseLeftBarClass<LeftBarClass> {
	
}
