package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUploadImg<M extends BaseUploadImg<M>> extends Model<M> implements IBean {

	public M setImgId(java.lang.Integer imgId) {
		set("img_Id", imgId);
		return (M)this;
	}
	
	public java.lang.Integer getImgId() {
		return getInt("img_Id");
	}

	public M setImgName(java.lang.String imgName) {
		set("img_Name", imgName);
		return (M)this;
	}
	
	public java.lang.String getImgName() {
		return getStr("img_Name");
	}

	public M setImgUpload(java.lang.String imgUpload) {
		set("img_Upload", imgUpload);
		return (M)this;
	}
	
	public java.lang.String getImgUpload() {
		return getStr("img_Upload");
	}

	public M setImgDesc(java.lang.String imgDesc) {
		set("img_Desc", imgDesc);
		return (M)this;
	}
	
	public java.lang.String getImgDesc() {
		return getStr("img_Desc");
	}

	public M setImgUrl(java.lang.String imgUrl) {
		set("img_Url", imgUrl);
		return (M)this;
	}
	
	public java.lang.String getImgUrl() {
		return getStr("img_Url");
	}

	public M setImgCustom(java.lang.String imgCustom) {
		set("img_Custom", imgCustom);
		return (M)this;
	}
	
	public java.lang.String getImgCustom() {
		return getStr("img_Custom");
	}

}
