package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticleMain<M extends BaseArticleMain<M>> extends Model<M> implements IBean {

	public M setArticleId(java.lang.String articleId) {
		set("article_Id", articleId);
		return (M)this;
	}
	
	public java.lang.String getArticleId() {
		return getStr("article_Id");
	}

	public M setArticleTitle(java.lang.String articleTitle) {
		set("article_Title", articleTitle);
		return (M)this;
	}
	
	public java.lang.String getArticleTitle() {
		return getStr("article_Title");
	}

	public M setArticleAbstract(java.lang.String articleAbstract) {
		set("article_Abstract", articleAbstract);
		return (M)this;
	}
	
	public java.lang.String getArticleAbstract() {
		return getStr("article_Abstract");
	}

	public M setArticleContent(java.lang.String articleContent) {
		set("article_Content", articleContent);
		return (M)this;
	}
	
	public java.lang.String getArticleContent() {
		return getStr("article_Content");
	}

	public M setArticleComments(java.lang.Integer articleComments) {
		set("article_Comments", articleComments);
		return (M)this;
	}
	
	public java.lang.Integer getArticleComments() {
		return getInt("article_Comments");
	}

	public M setArticleViews(java.lang.Integer articleViews) {
		set("article_Views", articleViews);
		return (M)this;
	}
	
	public java.lang.Integer getArticleViews() {
		return getInt("article_Views");
	}

	public M setArticleHeart(java.lang.Integer articleHeart) {
		set("article_Heart", articleHeart);
		return (M)this;
	}
	
	public java.lang.Integer getArticleHeart() {
		return getInt("article_Heart");
	}

	public M setArticleAuthor(java.lang.String articleAuthor) {
		set("article_Author", articleAuthor);
		return (M)this;
	}
	
	public java.lang.String getArticleAuthor() {
		return getStr("article_Author");
	}

	public M setArticleCustom(java.lang.String articleCustom) {
		set("article_Custom", articleCustom);
		return (M)this;
	}
	
	public java.lang.String getArticleCustom() {
		return getStr("article_Custom");
	}

}
