package com.cn.jblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeftBarClass<M extends BaseLeftBarClass<M>> extends Model<M> implements IBean {

	public M setClassId(java.lang.String classId) {
		set("class_Id", classId);
		return (M)this;
	}
	
	public java.lang.String getClassId() {
		return getStr("class_Id");
	}

	public M setClassName(java.lang.String className) {
		set("class_Name", className);
		return (M)this;
	}
	
	public java.lang.String getClassName() {
		return getStr("class_Name");
	}

	public M setClassTitle(java.lang.String classTitle) {
		set("class_Title", classTitle);
		return (M)this;
	}
	
	public java.lang.String getClassTitle() {
		return getStr("class_Title");
	}

	public M setClassDescription(java.lang.String classDescription) {
		set("class_Description", classDescription);
		return (M)this;
	}
	
	public java.lang.String getClassDescription() {
		return getStr("class_Description");
	}

	public M setClassUrl(java.lang.String classUrl) {
		set("class_Url", classUrl);
		return (M)this;
	}
	
	public java.lang.String getClassUrl() {
		return getStr("class_Url");
	}

	public M setClassType(java.lang.String classType) {
		set("class_Type", classType);
		return (M)this;
	}
	
	public java.lang.String getClassType() {
		return getStr("class_Type");
	}

	public M setClassCustom(java.lang.String classCustom) {
		set("class_Custom", classCustom);
		return (M)this;
	}
	
	public java.lang.String getClassCustom() {
		return getStr("class_Custom");
	}

}
